"""Add bank_transactions and customer_invoices tables

Revision ID: 2f33c4693fc8
Revises: 001
Create Date: 2026-02-06 16:37:20.429521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f33c4693fc8'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_org_number', sa.String(length=20), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_address', sa.Text(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('kid_number', sa.String(length=50), nullable=True),
    sa.Column('amount_excl_vat', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('ai_processed', sa.Boolean(), nullable=True),
    sa.Column('ai_confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_booking_suggestion', sa.JSON(), nullable=True),
    sa.Column('ai_detected_issues', sa.JSON(), nullable=True),
    sa.Column('booked_at', sa.DateTime(), nullable=True),
    sa.Column('ledger_entry_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['general_ledger.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_invoices_client_id'), 'customer_invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_customer_invoices_customer_name'), 'customer_invoices', ['customer_name'], unique=False)
    op.create_index(op.f('ix_customer_invoices_invoice_date'), 'customer_invoices', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_customer_invoices_invoice_number'), 'customer_invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_customer_invoices_kid_number'), 'customer_invoices', ['kid_number'], unique=False)
    op.create_index(op.f('ix_customer_invoices_payment_status'), 'customer_invoices', ['payment_status'], unique=False)
    op.drop_index('ix_agent_events_unprocessed', table_name='agent_events', postgresql_where='(processed = false)')
    op.alter_column('agent_learned_patterns', 'applies_to_clients',
               existing_type=postgresql.ARRAY(sa.UUID()),
               nullable=False)
    op.drop_index('ix_agent_learned_patterns_is_active', table_name='agent_learned_patterns')
    op.drop_index('ix_agent_tasks_claim', table_name='agent_tasks', postgresql_where="((status)::text = 'pending'::text)")
    op.alter_column('clients', 'ai_automation_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('FULL', 'ASSISTED', 'MANUAL', name='automationlevel'),
               existing_nullable=False)
    op.drop_constraint('uq_clients_org_number', 'clients', type_='unique')
    op.drop_index('ix_clients_org_number', table_name='clients')
    op.create_index(op.f('ix_clients_org_number'), 'clients', ['org_number'], unique=True)
    op.alter_column('documents', 'ocr_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('review_queue', 'priority',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='reviewpriority'),
               existing_nullable=False)
    op.alter_column('review_queue', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'IN_PROGRESS', 'APPROVED', 'CORRECTED', 'REJECTED', name='reviewstatus'),
               existing_nullable=False)
    op.alter_column('review_queue', 'issue_category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('LOW_CONFIDENCE', 'UNKNOWN_VENDOR', 'UNUSUAL_AMOUNT', 'MISSING_VAT', 'UNCLEAR_DESCRIPTION', 'DUPLICATE_INVOICE', 'PROCESSING_ERROR', 'MANUAL_REVIEW_REQUIRED', name='issuecategory'),
               existing_nullable=False)
    op.drop_index('ix_review_queue_status_priority', table_name='review_queue')
    op.alter_column('tenants', 'subscription_tier',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('BASIC', 'PROFESSIONAL', 'ENTERPRISE', name='subscriptiontier'),
               existing_nullable=False)
    op.drop_constraint('uq_tenants_org_number', 'tenants', type_='unique')
    op.drop_index('ix_tenants_org_number', table_name='tenants')
    op.create_index(op.f('ix_tenants_org_number'), 'tenants', ['org_number'], unique=True)
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.drop_index(op.f('ix_tenants_org_number'), table_name='tenants')
    op.create_index('ix_tenants_org_number', 'tenants', ['org_number'], unique=False)
    op.create_unique_constraint('uq_tenants_org_number', 'tenants', ['org_number'])
    op.alter_column('tenants', 'subscription_tier',
               existing_type=sa.Enum('BASIC', 'PROFESSIONAL', 'ENTERPRISE', name='subscriptiontier'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_index('ix_review_queue_status_priority', 'review_queue', ['status', 'priority'], unique=False)
    op.alter_column('review_queue', 'issue_category',
               existing_type=sa.Enum('LOW_CONFIDENCE', 'UNKNOWN_VENDOR', 'UNUSUAL_AMOUNT', 'MISSING_VAT', 'UNCLEAR_DESCRIPTION', 'DUPLICATE_INVOICE', 'PROCESSING_ERROR', 'MANUAL_REVIEW_REQUIRED', name='issuecategory'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('review_queue', 'status',
               existing_type=sa.Enum('PENDING', 'IN_PROGRESS', 'APPROVED', 'CORRECTED', 'REJECTED', name='reviewstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('review_queue', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='reviewpriority'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('documents', 'ocr_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_clients_org_number'), table_name='clients')
    op.create_index('ix_clients_org_number', 'clients', ['org_number'], unique=False)
    op.create_unique_constraint('uq_clients_org_number', 'clients', ['org_number'])
    op.alter_column('clients', 'ai_automation_level',
               existing_type=sa.Enum('FULL', 'ASSISTED', 'MANUAL', name='automationlevel'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_index('ix_agent_tasks_claim', 'agent_tasks', ['agent_type', 'status', 'priority', 'created_at'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.create_index('ix_agent_learned_patterns_is_active', 'agent_learned_patterns', ['is_active'], unique=False)
    op.alter_column('agent_learned_patterns', 'applies_to_clients',
               existing_type=postgresql.ARRAY(sa.UUID()),
               nullable=True)
    op.create_index('ix_agent_events_unprocessed', 'agent_events', ['processed', 'created_at'], unique=False, postgresql_where='(processed = false)')
    op.drop_index(op.f('ix_customer_invoices_payment_status'), table_name='customer_invoices')
    op.drop_index(op.f('ix_customer_invoices_kid_number'), table_name='customer_invoices')
    op.drop_index(op.f('ix_customer_invoices_invoice_number'), table_name='customer_invoices')
    op.drop_index(op.f('ix_customer_invoices_invoice_date'), table_name='customer_invoices')
    op.drop_index(op.f('ix_customer_invoices_customer_name'), table_name='customer_invoices')
    op.drop_index(op.f('ix_customer_invoices_client_id'), table_name='customer_invoices')
    op.drop_table('customer_invoices')
    # ### end Alembic commands ###
